
services:

  mysql:
    image: mysql:8.0
    container_name: 'mysql8'
    volumes:
      - .\mysql\data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
     
  adminer:
    image: adminer
    container_name: 'adminer'
    ports:
      - 8090:8080



  keycloak1:
    image: quay.io/keycloak/keycloak:26.0
    container_name: 'keycloak1'
    hostname: keycloak1
    volumes:
      #- ./keycloak1/conf/:/opt/keycloak/conf/
      - ./keycloak1/data/:/opt/keycloak/data/
    environment:
    
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql:3306/keycloak
      KC_DB_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      
      KC_HTTP_RELATIVE_PATH: /auth  
      
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: true
      
      KC_HOSTNAME_STRICT: "false"
      
      QUARKUS_HTTP_ACCESS_LOG_ENABLED: true
      QUARKUS_HTTP_ACCESS_LOG_LOG_TO_FILE: true
      QUARKUS_HTTP_ACCESS_LOG_LOG_DIRECTORY: /opt/keycloak/data/log/
      QUARKUS_HTTP_ACCESS_LOG_PATTERN: combined
      QUARKUS_HTTP_ACCESS_LOG_ROTATE: true
      
    #ports:
    #  - 8080:8080
    command: 
      - start
      #- --log=console,file
      #- --log-level=INFO
    depends_on:
      - mysql

  keycloak2:
    image: quay.io/keycloak/keycloak:26.0
    container_name: 'keycloak2'
    hostname: keycloak2
    volumes:
      #- ./keycloak1/conf/:/opt/keycloak/conf/
      - ./keycloak2/data/:/opt/keycloak/data/
    environment:
    
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql:3306/keycloak
      KC_DB_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      
      KC_HTTP_RELATIVE_PATH: /auth  
      
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: true
      
      KC_HOSTNAME_STRICT: "false"
      
      QUARKUS_HTTP_ACCESS_LOG_ENABLED: true
      QUARKUS_HTTP_ACCESS_LOG_LOG_TO_FILE: true
      QUARKUS_HTTP_ACCESS_LOG_LOG_DIRECTORY: /opt/keycloak/data/log/
      QUARKUS_HTTP_ACCESS_LOG_PATTERN: combined
      QUARKUS_HTTP_ACCESS_LOG_ROTATE: true
      
    #ports:
    #  - 8080:8080
    command: 
      - start
      #- --log=console,file
      #- --log-level=INFO
    depends_on:
      - mysql
      
      

  nginx:
    image: nginx:latest
    container_name: 'nginx'
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/log:/var/log/nginx
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    depends_on:
      - keycloak1
      - keycloak2

